behaviors:
  CollisionAvoidance:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 5120
      learning_rate: 0.00035
      beta: 0.0025
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 264
      num_layers: 3

    keep_checkpoints: 15
    checkpoint_interval: 1000000
    time_horizon: 264
    max_steps: 50000000
    summary_freq: 100000
    threaded: true

  CollisionAvoidanceSAC:
    trainer_type: sac
    hyperparameters: 
      batch_size: 256
      buffer_size: 10000
      learning_rate: 0.00035
      buffer_init_steps: 5000
      init_entcoef: 0.5
      steps_per_update: 1
      learning_rate_schedule: constant

    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 3

    reward_signals:
      extrinsic:
        gamma: 0.75
        strength: 0.99

    keep_checkpoints: 15
    checkpoint_interval: 1000000
    time_horizon: 264
    max_steps: 50000000
    summary_freq: 10000
    threaded: true
